# Generated by Django 2.1.15 on 2020-09-16 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_auto_20200913_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocliente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
